package com.think.firewaiter.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.think.firewaiter.module.Office;
import com.think.firewaiter.module.User;
import com.think.firewaiter.module.PxProductInfo;
import com.think.firewaiter.module.PxProductCategory;
import com.think.firewaiter.module.PxFormatInfo;
import com.think.firewaiter.module.PxMethodInfo;
import com.think.firewaiter.module.PxTableInfo;
import com.think.firewaiter.module.PxProductFormatRel;
import com.think.firewaiter.module.PxProductMethodRef;
import com.think.firewaiter.module.ShoppingCart;
import com.think.firewaiter.module.UserTableRel;
import com.think.firewaiter.module.PxOptReason;
import com.think.firewaiter.module.PxProductRemarks;
import com.think.firewaiter.module.PxTableArea;
import com.think.firewaiter.module.PxPromotioInfo;
import com.think.firewaiter.module.PxPromotioDetails;

import com.think.firewaiter.dao.OfficeDao;
import com.think.firewaiter.dao.UserDao;
import com.think.firewaiter.dao.PxProductInfoDao;
import com.think.firewaiter.dao.PxProductCategoryDao;
import com.think.firewaiter.dao.PxFormatInfoDao;
import com.think.firewaiter.dao.PxMethodInfoDao;
import com.think.firewaiter.dao.PxTableInfoDao;
import com.think.firewaiter.dao.PxProductFormatRelDao;
import com.think.firewaiter.dao.PxProductMethodRefDao;
import com.think.firewaiter.dao.ShoppingCartDao;
import com.think.firewaiter.dao.UserTableRelDao;
import com.think.firewaiter.dao.PxOptReasonDao;
import com.think.firewaiter.dao.PxProductRemarksDao;
import com.think.firewaiter.dao.PxTableAreaDao;
import com.think.firewaiter.dao.PxPromotioInfoDao;
import com.think.firewaiter.dao.PxPromotioDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig officeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig pxProductInfoDaoConfig;
    private final DaoConfig pxProductCategoryDaoConfig;
    private final DaoConfig pxFormatInfoDaoConfig;
    private final DaoConfig pxMethodInfoDaoConfig;
    private final DaoConfig pxTableInfoDaoConfig;
    private final DaoConfig pxProductFormatRelDaoConfig;
    private final DaoConfig pxProductMethodRefDaoConfig;
    private final DaoConfig shoppingCartDaoConfig;
    private final DaoConfig userTableRelDaoConfig;
    private final DaoConfig pxOptReasonDaoConfig;
    private final DaoConfig pxProductRemarksDaoConfig;
    private final DaoConfig pxTableAreaDaoConfig;
    private final DaoConfig pxPromotioInfoDaoConfig;
    private final DaoConfig pxPromotioDetailsDaoConfig;

    private final OfficeDao officeDao;
    private final UserDao userDao;
    private final PxProductInfoDao pxProductInfoDao;
    private final PxProductCategoryDao pxProductCategoryDao;
    private final PxFormatInfoDao pxFormatInfoDao;
    private final PxMethodInfoDao pxMethodInfoDao;
    private final PxTableInfoDao pxTableInfoDao;
    private final PxProductFormatRelDao pxProductFormatRelDao;
    private final PxProductMethodRefDao pxProductMethodRefDao;
    private final ShoppingCartDao shoppingCartDao;
    private final UserTableRelDao userTableRelDao;
    private final PxOptReasonDao pxOptReasonDao;
    private final PxProductRemarksDao pxProductRemarksDao;
    private final PxTableAreaDao pxTableAreaDao;
    private final PxPromotioInfoDao pxPromotioInfoDao;
    private final PxPromotioDetailsDao pxPromotioDetailsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        officeDaoConfig = daoConfigMap.get(OfficeDao.class).clone();
        officeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        pxProductInfoDaoConfig = daoConfigMap.get(PxProductInfoDao.class).clone();
        pxProductInfoDaoConfig.initIdentityScope(type);

        pxProductCategoryDaoConfig = daoConfigMap.get(PxProductCategoryDao.class).clone();
        pxProductCategoryDaoConfig.initIdentityScope(type);

        pxFormatInfoDaoConfig = daoConfigMap.get(PxFormatInfoDao.class).clone();
        pxFormatInfoDaoConfig.initIdentityScope(type);

        pxMethodInfoDaoConfig = daoConfigMap.get(PxMethodInfoDao.class).clone();
        pxMethodInfoDaoConfig.initIdentityScope(type);

        pxTableInfoDaoConfig = daoConfigMap.get(PxTableInfoDao.class).clone();
        pxTableInfoDaoConfig.initIdentityScope(type);

        pxProductFormatRelDaoConfig = daoConfigMap.get(PxProductFormatRelDao.class).clone();
        pxProductFormatRelDaoConfig.initIdentityScope(type);

        pxProductMethodRefDaoConfig = daoConfigMap.get(PxProductMethodRefDao.class).clone();
        pxProductMethodRefDaoConfig.initIdentityScope(type);

        shoppingCartDaoConfig = daoConfigMap.get(ShoppingCartDao.class).clone();
        shoppingCartDaoConfig.initIdentityScope(type);

        userTableRelDaoConfig = daoConfigMap.get(UserTableRelDao.class).clone();
        userTableRelDaoConfig.initIdentityScope(type);

        pxOptReasonDaoConfig = daoConfigMap.get(PxOptReasonDao.class).clone();
        pxOptReasonDaoConfig.initIdentityScope(type);

        pxProductRemarksDaoConfig = daoConfigMap.get(PxProductRemarksDao.class).clone();
        pxProductRemarksDaoConfig.initIdentityScope(type);

        pxTableAreaDaoConfig = daoConfigMap.get(PxTableAreaDao.class).clone();
        pxTableAreaDaoConfig.initIdentityScope(type);

        pxPromotioInfoDaoConfig = daoConfigMap.get(PxPromotioInfoDao.class).clone();
        pxPromotioInfoDaoConfig.initIdentityScope(type);

        pxPromotioDetailsDaoConfig = daoConfigMap.get(PxPromotioDetailsDao.class).clone();
        pxPromotioDetailsDaoConfig.initIdentityScope(type);

        officeDao = new OfficeDao(officeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        pxProductInfoDao = new PxProductInfoDao(pxProductInfoDaoConfig, this);
        pxProductCategoryDao = new PxProductCategoryDao(pxProductCategoryDaoConfig, this);
        pxFormatInfoDao = new PxFormatInfoDao(pxFormatInfoDaoConfig, this);
        pxMethodInfoDao = new PxMethodInfoDao(pxMethodInfoDaoConfig, this);
        pxTableInfoDao = new PxTableInfoDao(pxTableInfoDaoConfig, this);
        pxProductFormatRelDao = new PxProductFormatRelDao(pxProductFormatRelDaoConfig, this);
        pxProductMethodRefDao = new PxProductMethodRefDao(pxProductMethodRefDaoConfig, this);
        shoppingCartDao = new ShoppingCartDao(shoppingCartDaoConfig, this);
        userTableRelDao = new UserTableRelDao(userTableRelDaoConfig, this);
        pxOptReasonDao = new PxOptReasonDao(pxOptReasonDaoConfig, this);
        pxProductRemarksDao = new PxProductRemarksDao(pxProductRemarksDaoConfig, this);
        pxTableAreaDao = new PxTableAreaDao(pxTableAreaDaoConfig, this);
        pxPromotioInfoDao = new PxPromotioInfoDao(pxPromotioInfoDaoConfig, this);
        pxPromotioDetailsDao = new PxPromotioDetailsDao(pxPromotioDetailsDaoConfig, this);

        registerDao(Office.class, officeDao);
        registerDao(User.class, userDao);
        registerDao(PxProductInfo.class, pxProductInfoDao);
        registerDao(PxProductCategory.class, pxProductCategoryDao);
        registerDao(PxFormatInfo.class, pxFormatInfoDao);
        registerDao(PxMethodInfo.class, pxMethodInfoDao);
        registerDao(PxTableInfo.class, pxTableInfoDao);
        registerDao(PxProductFormatRel.class, pxProductFormatRelDao);
        registerDao(PxProductMethodRef.class, pxProductMethodRefDao);
        registerDao(ShoppingCart.class, shoppingCartDao);
        registerDao(UserTableRel.class, userTableRelDao);
        registerDao(PxOptReason.class, pxOptReasonDao);
        registerDao(PxProductRemarks.class, pxProductRemarksDao);
        registerDao(PxTableArea.class, pxTableAreaDao);
        registerDao(PxPromotioInfo.class, pxPromotioInfoDao);
        registerDao(PxPromotioDetails.class, pxPromotioDetailsDao);
    }
    
    public void clear() {
        officeDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        pxProductInfoDaoConfig.getIdentityScope().clear();
        pxProductCategoryDaoConfig.getIdentityScope().clear();
        pxFormatInfoDaoConfig.getIdentityScope().clear();
        pxMethodInfoDaoConfig.getIdentityScope().clear();
        pxTableInfoDaoConfig.getIdentityScope().clear();
        pxProductFormatRelDaoConfig.getIdentityScope().clear();
        pxProductMethodRefDaoConfig.getIdentityScope().clear();
        shoppingCartDaoConfig.getIdentityScope().clear();
        userTableRelDaoConfig.getIdentityScope().clear();
        pxOptReasonDaoConfig.getIdentityScope().clear();
        pxProductRemarksDaoConfig.getIdentityScope().clear();
        pxTableAreaDaoConfig.getIdentityScope().clear();
        pxPromotioInfoDaoConfig.getIdentityScope().clear();
        pxPromotioDetailsDaoConfig.getIdentityScope().clear();
    }

    public OfficeDao getOfficeDao() {
        return officeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PxProductInfoDao getPxProductInfoDao() {
        return pxProductInfoDao;
    }

    public PxProductCategoryDao getPxProductCategoryDao() {
        return pxProductCategoryDao;
    }

    public PxFormatInfoDao getPxFormatInfoDao() {
        return pxFormatInfoDao;
    }

    public PxMethodInfoDao getPxMethodInfoDao() {
        return pxMethodInfoDao;
    }

    public PxTableInfoDao getPxTableInfoDao() {
        return pxTableInfoDao;
    }

    public PxProductFormatRelDao getPxProductFormatRelDao() {
        return pxProductFormatRelDao;
    }

    public PxProductMethodRefDao getPxProductMethodRefDao() {
        return pxProductMethodRefDao;
    }

    public ShoppingCartDao getShoppingCartDao() {
        return shoppingCartDao;
    }

    public UserTableRelDao getUserTableRelDao() {
        return userTableRelDao;
    }

    public PxOptReasonDao getPxOptReasonDao() {
        return pxOptReasonDao;
    }

    public PxProductRemarksDao getPxProductRemarksDao() {
        return pxProductRemarksDao;
    }

    public PxTableAreaDao getPxTableAreaDao() {
        return pxTableAreaDao;
    }

    public PxPromotioInfoDao getPxPromotioInfoDao() {
        return pxPromotioInfoDao;
    }

    public PxPromotioDetailsDao getPxPromotioDetailsDao() {
        return pxPromotioDetailsDao;
    }

}
