package com.think.firewaiter.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.think.firewaiter.module.PxMethodInfo;
import com.think.firewaiter.module.PxProductInfo;

import com.think.firewaiter.module.PxProductMethodRef;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PxProductMethodRef".
*/
public class PxProductMethodRefDao extends AbstractDao<PxProductMethodRef, Long> {

    public static final String TABLENAME = "PxProductMethodRef";

    /**
     * Properties of entity PxProductMethodRef.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property DelFlag = new Property(2, String.class, "delFlag", false, "DEL_FLAG");
        public final static Property PxMethodInfoId = new Property(3, Long.class, "pxMethodInfoId", false, "PX_METHOD_INFO_ID");
        public final static Property PxProductInfoId = new Property(4, Long.class, "pxProductInfoId", false, "PX_PRODUCT_INFO_ID");
    };

    private DaoSession daoSession;


    public PxProductMethodRefDao(DaoConfig config) {
        super(config);
    }
    
    public PxProductMethodRefDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PxProductMethodRef\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"DEL_FLAG\" TEXT," + // 2: delFlag
                "\"PX_METHOD_INFO_ID\" INTEGER," + // 3: pxMethodInfoId
                "\"PX_PRODUCT_INFO_ID\" INTEGER);"); // 4: pxProductInfoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PxProductMethodRef\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PxProductMethodRef entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(3, delFlag);
        }
 
        Long pxMethodInfoId = entity.getPxMethodInfoId();
        if (pxMethodInfoId != null) {
            stmt.bindLong(4, pxMethodInfoId);
        }
 
        Long pxProductInfoId = entity.getPxProductInfoId();
        if (pxProductInfoId != null) {
            stmt.bindLong(5, pxProductInfoId);
        }
    }

    @Override
    protected void attachEntity(PxProductMethodRef entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PxProductMethodRef readEntity(Cursor cursor, int offset) {
        PxProductMethodRef entity = new PxProductMethodRef( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // delFlag
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // pxMethodInfoId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // pxProductInfoId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PxProductMethodRef entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDelFlag(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPxMethodInfoId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setPxProductInfoId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PxProductMethodRef entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PxProductMethodRef entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxMethodInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPxProductInfoDao().getAllColumns());
            builder.append(" FROM PxProductMethodRef T");
            builder.append(" LEFT JOIN MethodInfo T0 ON T.\"PX_METHOD_INFO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ProductInfo T1 ON T.\"PX_PRODUCT_INFO_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PxProductMethodRef loadCurrentDeep(Cursor cursor, boolean lock) {
        PxProductMethodRef entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxMethodInfo dbMethod = loadCurrentOther(daoSession.getPxMethodInfoDao(), cursor, offset);
        entity.setDbMethod(dbMethod);
        offset += daoSession.getPxMethodInfoDao().getAllColumns().length;

        PxProductInfo dbProduct = loadCurrentOther(daoSession.getPxProductInfoDao(), cursor, offset);
        entity.setDbProduct(dbProduct);

        return entity;    
    }

    public PxProductMethodRef loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PxProductMethodRef> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PxProductMethodRef> list = new ArrayList<PxProductMethodRef>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PxProductMethodRef> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PxProductMethodRef> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
