package com.think.firewaiter.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.think.firewaiter.module.PxFormatInfo;
import com.think.firewaiter.module.PxProductInfo;
import com.think.firewaiter.module.PxPromotioInfo;

import com.think.firewaiter.module.PxPromotioDetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PromotioDetails".
*/
public class PxPromotioDetailsDao extends AbstractDao<PxPromotioDetails, Long> {

    public static final String TABLENAME = "PromotioDetails";

    /**
     * Properties of entity PxPromotioDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ObjectId = new Property(1, String.class, "objectId", false, "OBJECT_ID");
        public final static Property PromotionalPrice = new Property(2, Double.class, "promotionalPrice", false, "PROMOTIONAL_PRICE");
        public final static Property DelFlag = new Property(3, String.class, "delFlag", false, "DEL_FLAG");
        public final static Property PxProductInfoId = new Property(4, long.class, "pxProductInfoId", false, "PX_PRODUCT_INFO_ID");
        public final static Property PxFormatId = new Property(5, Long.class, "pxFormatId", false, "PX_FORMAT_ID");
        public final static Property PxPromotioInfoId = new Property(6, long.class, "pxPromotioInfoId", false, "PX_PROMOTIO_INFO_ID");
    };

    private DaoSession daoSession;

    private Query<PxPromotioDetails> pxPromotioInfo_DbPromDetailsListQuery;

    public PxPromotioDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public PxPromotioDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PromotioDetails\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ASC ," + // 0: id
                "\"OBJECT_ID\" TEXT," + // 1: objectId
                "\"PROMOTIONAL_PRICE\" REAL," + // 2: promotionalPrice
                "\"DEL_FLAG\" TEXT," + // 3: delFlag
                "\"PX_PRODUCT_INFO_ID\" INTEGER NOT NULL ," + // 4: pxProductInfoId
                "\"PX_FORMAT_ID\" INTEGER," + // 5: pxFormatId
                "\"PX_PROMOTIO_INFO_ID\" INTEGER NOT NULL );"); // 6: pxPromotioInfoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PromotioDetails\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PxPromotioDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String objectId = entity.getObjectId();
        if (objectId != null) {
            stmt.bindString(2, objectId);
        }
 
        Double promotionalPrice = entity.getPromotionalPrice();
        if (promotionalPrice != null) {
            stmt.bindDouble(3, promotionalPrice);
        }
 
        String delFlag = entity.getDelFlag();
        if (delFlag != null) {
            stmt.bindString(4, delFlag);
        }
        stmt.bindLong(5, entity.getPxProductInfoId());
 
        Long pxFormatId = entity.getPxFormatId();
        if (pxFormatId != null) {
            stmt.bindLong(6, pxFormatId);
        }
        stmt.bindLong(7, entity.getPxPromotioInfoId());
    }

    @Override
    protected void attachEntity(PxPromotioDetails entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PxPromotioDetails readEntity(Cursor cursor, int offset) {
        PxPromotioDetails entity = new PxPromotioDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // objectId
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // promotionalPrice
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // delFlag
            cursor.getLong(offset + 4), // pxProductInfoId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // pxFormatId
            cursor.getLong(offset + 6) // pxPromotioInfoId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PxPromotioDetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setObjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPromotionalPrice(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setDelFlag(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPxProductInfoId(cursor.getLong(offset + 4));
        entity.setPxFormatId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setPxPromotioInfoId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PxPromotioDetails entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PxPromotioDetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dbPromDetailsList" to-many relationship of PxPromotioInfo. */
    public List<PxPromotioDetails> _queryPxPromotioInfo_DbPromDetailsList(long pxPromotioInfoId) {
        synchronized (this) {
            if (pxPromotioInfo_DbPromDetailsListQuery == null) {
                QueryBuilder<PxPromotioDetails> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PxPromotioInfoId.eq(null));
                pxPromotioInfo_DbPromDetailsListQuery = queryBuilder.build();
            }
        }
        Query<PxPromotioDetails> query = pxPromotioInfo_DbPromDetailsListQuery.forCurrentThread();
        query.setParameter(0, pxPromotioInfoId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPxProductInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPxFormatInfoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getPxPromotioInfoDao().getAllColumns());
            builder.append(" FROM PromotioDetails T");
            builder.append(" LEFT JOIN ProductInfo T0 ON T.\"PX_PRODUCT_INFO_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN FormatInfo T1 ON T.\"PX_FORMAT_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN PromotioInfo T2 ON T.\"PX_PROMOTIO_INFO_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PxPromotioDetails loadCurrentDeep(Cursor cursor, boolean lock) {
        PxPromotioDetails entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PxProductInfo dbProduct = loadCurrentOther(daoSession.getPxProductInfoDao(), cursor, offset);
         if(dbProduct != null) {
            entity.setDbProduct(dbProduct);
        }
        offset += daoSession.getPxProductInfoDao().getAllColumns().length;

        PxFormatInfo dbFormat = loadCurrentOther(daoSession.getPxFormatInfoDao(), cursor, offset);
        entity.setDbFormat(dbFormat);
        offset += daoSession.getPxFormatInfoDao().getAllColumns().length;

        PxPromotioInfo dbPromotio = loadCurrentOther(daoSession.getPxPromotioInfoDao(), cursor, offset);
         if(dbPromotio != null) {
            entity.setDbPromotio(dbPromotio);
        }

        return entity;    
    }

    public PxPromotioDetails loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PxPromotioDetails> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PxPromotioDetails> list = new ArrayList<PxPromotioDetails>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PxPromotioDetails> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PxPromotioDetails> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
