package com.think.firewaiter.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "Office".
 */
public class Office implements java.io.Serializable {

    private Long id;
    /**
     * 对应服务器id
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 机构编码
     */
     @Expose
    private String code;
    /**
     * 机构类型（1：公司；2：部门；3：小组）
     */
     @Expose
    private String type;
    /**
     * 机构等级（1：一级；2：二级；3：三级；4：四级）
     */
     @Expose
    private String grade;
    /**
     * 联系地址
     */
     @Expose
    private String address;
    /**
     * 邮政编码
     */
     @Expose
    private String zipCode;
    /**
     * 负责人
     */
     @Expose
    private String master;
    /**
     * 电话
     */
     @Expose
    private String phone;
    /**
     * 传真
     */
     @Expose
    private String fax;
    /**
     * 邮箱
     */
     @Expose
    private String email;
    /**
     * 是否可用 (0:可用 1:不可用) 
     */
     @Expose
    private String useable;
    /**
     * 店铺logo
     */
     @Expose
    private String logo;
    /**
     * 群组id
     */
     @Expose
    private String groupId;
    /**
     * 店铺名字
     */
     @Expose
    private String name;
    /**
     * 环信收银端用户名
     */
     @Expose
    private String easeAdmin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Office() {
    }

    public Office(Long id) {
        this.id = id;
    }

    public Office(Long id, String objectId, String code, String type, String grade, String address, String zipCode, String master, String phone, String fax, String email, String useable, String logo, String groupId, String name, String easeAdmin) {
        this.id = id;
        this.objectId = objectId;
        this.code = code;
        this.type = type;
        this.grade = grade;
        this.address = address;
        this.zipCode = zipCode;
        this.master = master;
        this.phone = phone;
        this.fax = fax;
        this.email = email;
        this.useable = useable;
        this.logo = logo;
        this.groupId = groupId;
        this.name = name;
        this.easeAdmin = easeAdmin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getMaster() {
        return master;
    }

    public void setMaster(String master) {
        this.master = master;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUseable() {
        return useable;
    }

    public void setUseable(String useable) {
        this.useable = useable;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEaseAdmin() {
        return easeAdmin;
    }

    public void setEaseAdmin(String easeAdmin) {
        this.easeAdmin = easeAdmin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
