package com.think.firewaiter.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END

/**
 * 操作原因
 */
public class PxOptReason implements java.io.Serializable {

    private Long id;
    /**
     * 对应服务器id
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 原因
     */
     @Expose
    private String name;
    /**
     * 类型(0:打折原因 1：撤单原因 2：取消结账原因 3：退货原因)
     */
     @Expose
    private String type;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;

    // KEEP FIELDS - put your custom fields here
    public static final String DISCOUNT_REASON = "0";
    public static final String REVOKE_REASON = "1";
    public static final String CANCEL_CHECKOUT_REASON = "2";
    public static final String REFUND_REASON = "3";
    // KEEP FIELDS END

    public PxOptReason() {
    }

    public PxOptReason(Long id) {
        this.id = id;
    }

    public PxOptReason(Long id, String objectId, String name, String type, String delFlag) {
        this.id = id;
        this.objectId = objectId;
        this.name = name;
        this.type = type;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
