package com.think.firewaiter.module;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "User".
 */
public class User implements java.io.Serializable {

    private Long id;
    /**
     * 
     */
     @SerializedName("id") @Expose
    private String objectId;
    /**
     * 登录名
     */
     @Expose
    private String loginName;
    /**
     * 密码
     */
     @Expose
    private String password;
    /**
     * 工号
     */
     @Expose
    private String no;
    /**
     * 姓名
     */
     @Expose
    private String name;
    /**
     * 邮箱
     */
     @Expose
    private String email;
    /**
     * 电话
     */
     @Expose
    private String phone;
    /**
     * 手机
     */
     @Expose
    private String mobile;
    /**
     * 用户类型
     */
     @Expose
    private String userType;
    /**
     * 最后登陆IP
     */
     @Expose
    private String loginIp;
    /**
     * 最后登陆日期
     */
     @Expose
    private java.util.Date loginDate;
    /**
     * 是否允许登陆
     */
     @Expose
    private String loginFlag;
    /**
     * 头像
     */
     @Expose
    private String photo;
    /**
     * 原登录名
     */
     @Expose
    private String oldLoginName;
    /**
     * 新密码
     */
     @Expose
    private String newPassword;
    /**
     * 上次登陆IP
     */
     @Expose
    private String oldLoginIp;
    /**
     * 上次登陆日期
     */
     @Expose
    private java.util.Date oldLoginDate;
    /**
     * 虚拟删除 0：正常 1：删除 2：审核
     */
     @Expose
    private String delFlag;
    /**
     * 最大抹零限制
     */
     @Expose
    private Double maxTail;
    /**
     * 公司编码
     */
     @Expose
    private String companyCode;
    /**
     * 初始登录名
     */
     @Expose
    private String imUserName;
    /**
     * 初始化密码
     */
     @Expose
    private String initPassword;
    /**
     * 是否允许退菜(1:允许 0:不允许)
     */
     @Expose
    private String canRetreat;

    // KEEP FIELDS - put your custom fields here
  //Smack聊天密码
  private String mChatPwd;
  //能退菜
  public static final String CAN_RETREAT = "1";
  //不能退菜
  public static final String CAN_NOT_RETREAT = "0";
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String objectId, String loginName, String password, String no, String name, String email, String phone, String mobile, String userType, String loginIp, java.util.Date loginDate, String loginFlag, String photo, String oldLoginName, String newPassword, String oldLoginIp, java.util.Date oldLoginDate, String delFlag, Double maxTail, String companyCode, String imUserName, String initPassword, String canRetreat) {
        this.id = id;
        this.objectId = objectId;
        this.loginName = loginName;
        this.password = password;
        this.no = no;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.userType = userType;
        this.loginIp = loginIp;
        this.loginDate = loginDate;
        this.loginFlag = loginFlag;
        this.photo = photo;
        this.oldLoginName = oldLoginName;
        this.newPassword = newPassword;
        this.oldLoginIp = oldLoginIp;
        this.oldLoginDate = oldLoginDate;
        this.delFlag = delFlag;
        this.maxTail = maxTail;
        this.companyCode = companyCode;
        this.imUserName = imUserName;
        this.initPassword = initPassword;
        this.canRetreat = canRetreat;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getLoginIp() {
        return loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public java.util.Date getLoginDate() {
        return loginDate;
    }

    public void setLoginDate(java.util.Date loginDate) {
        this.loginDate = loginDate;
    }

    public String getLoginFlag() {
        return loginFlag;
    }

    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getOldLoginName() {
        return oldLoginName;
    }

    public void setOldLoginName(String oldLoginName) {
        this.oldLoginName = oldLoginName;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getOldLoginIp() {
        return oldLoginIp;
    }

    public void setOldLoginIp(String oldLoginIp) {
        this.oldLoginIp = oldLoginIp;
    }

    public java.util.Date getOldLoginDate() {
        return oldLoginDate;
    }

    public void setOldLoginDate(java.util.Date oldLoginDate) {
        this.oldLoginDate = oldLoginDate;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public Double getMaxTail() {
        return maxTail;
    }

    public void setMaxTail(Double maxTail) {
        this.maxTail = maxTail;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getImUserName() {
        return imUserName;
    }

    public void setImUserName(String imUserName) {
        this.imUserName = imUserName;
    }

    public String getInitPassword() {
        return initPassword;
    }

    public void setInitPassword(String initPassword) {
        this.initPassword = initPassword;
    }

    public String getCanRetreat() {
        return canRetreat;
    }

    public void setCanRetreat(String canRetreat) {
        this.canRetreat = canRetreat;
    }

    // KEEP METHODS - put your custom methods here

  public String getChatPwd() {
    return mChatPwd;
  }

  public void setChatPwd(String chatPwd) {
    mChatPwd = chatPwd;
  }
    // KEEP METHODS END

}
